function drawBat(x, y, flapT, sc) {
    ctx.save();
    ctx.translate(x, y);
    ctx.scale(sc, sc);
    const wing = Math.sin(flapT) * 10;
    ctx.fillStyle = 'rgba(30,10,40,0.8)';
    ctx.beginPath();
    ctx.moveTo(0, 0);
    ctx.bezierCurveTo(-8, wing - 4, -16, wing, -18, wing + 2);
    ctx.bezierCurveTo(-14, wing - 2, -8, wing - 6, 0, 2);
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(0, 0);
    ctx.bezierCurveTo(8, wing - 4, 16, wing, 18, wing + 2);
    ctx.bezierCurveTo(14, wing - 2, 8, wing - 6, 0, 2);
    ctx.fill();
    ctx.fillStyle = 'rgba(40,15,50,0.9)';
    ctx.beginPath();
    ctx.ellipse(0, 0, 4, 5, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.beginPath();
    ctx.arc(0, -5, 3, 0, Math.PI * 2);
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(-3, -7);
    ctx.lineTo(-5, -12);
    ctx.lineTo(-1, -8);
    ctx.closePath();
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(3, -7);
    ctx.lineTo(5, -12);
    ctx.lineTo(1, -8);
    ctx.closePath();
    ctx.fill();
    ctx.restore();
}
