// belgian hare
// (apologies for the artistic license)
function drawBunny(bx, by, arcT) {
    const lift = Math.sin(arcT * Math.PI) * 24;
    ctx.save();
    ctx.translate(bx, by);
    ctx.save();
    const ss = lerp(1, 0.45, lift / 24);
    ctx.fillStyle = 'rgba(0,0,0,0.18)';
    ctx.beginPath();
    ctx.ellipse(0, 2, 22 * ss, 5 * ss, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();
    ctx.translate(0, -lift);

    const body = '#8B3A10', dark = '#5c2208', lite = '#c0622a', belly = '#c8905a';
    ctx.fillStyle = dark;
    ctx.beginPath();
    ctx.ellipse(-10, 4, 14, 6, -0.3, 0, Math.PI * 2);
    ctx.fill();
    const kick = Math.sin(arcT * Math.PI) * 10;
    ctx.beginPath();
    ctx.ellipse(-18 - kick * 0.6, 6, 11, 4, -0.15, 0, Math.PI * 2);
    ctx.fill();
    const bg2 = ctx.createRadialGradient(2, -10, 3, -2, -8, 22);
    bg2.addColorStop(0, lite);
    bg2.addColorStop(0.5, body);
    bg2.addColorStop(1, dark);
    ctx.fillStyle = bg2;
    ctx.beginPath();
    ctx.ellipse(-2, -8, 18, 13, 0.15, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = belly;
    ctx.beginPath();
    ctx.ellipse(-4, -5, 8, 7, 0, 0, Math.PI * 2);
    ctx.fill();
    const ftuck = Math.sin(arcT * Math.PI) * 6;
    ctx.strokeStyle = dark;
    ctx.lineWidth = 5;
    ctx.lineCap = 'round';
    ctx.beginPath();
    ctx.moveTo(8, -4);
    ctx.lineTo(13, -4 + ftuck);
    ctx.stroke();
    ctx.beginPath();
    ctx.moveTo(4, -4);
    ctx.lineTo(8, -4 + ftuck * 0.6);
    ctx.stroke();
    ctx.fillStyle = '#ede8e0';
    ctx.beginPath();
    ctx.arc(-16, -5, 5, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#fff';
    ctx.beginPath();
    ctx.arc(-15, -6, 3, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = body;
    ctx.beginPath();
    ctx.ellipse(12, -16, 8, 7, 0.4, 0, Math.PI * 2);
    ctx.fill();
    const hx = 18, hy2 = -27;
    ctx.fillStyle = body;
    ctx.beginPath();
    ctx.ellipse(hx, hy2, 13, 11, 0.1, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = lite;
    ctx.beginPath();
    ctx.ellipse(hx + 10, hy2 + 3, 8, 5.5, 0.1, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = dark;
    ctx.beginPath();
    ctx.moveTo(hx - 5, hy2 - 7);
    ctx.bezierCurveTo(hx - 10, hy2 - 28, hx - 13, hy2 - 37, hx - 10, hy2 - 41);
    ctx.bezierCurveTo(hx - 6, hy2 - 37, hx - 3, hy2 - 27, hx - 3, hy2 - 7);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = body;
    ctx.beginPath();
    ctx.moveTo(hx + 1, hy2 - 8);
    ctx.bezierCurveTo(hx - 3, hy2 - 30, hx - 7, hy2 - 40, hx - 4, hy2 - 44);
    ctx.bezierCurveTo(hx, hy2 - 40, hx + 4, hy2 - 29, hx + 5, hy2 - 8);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = '#c06868';
    ctx.beginPath();
    ctx.moveTo(hx, hy2 - 9);
    ctx.bezierCurveTo(hx - 2, hy2 - 28, hx - 5, hy2 - 38, hx - 3, hy2 - 42);
    ctx.bezierCurveTo(hx - 1, hy2 - 38, hx + 2, hy2 - 27, hx + 3, hy2 - 9);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = '#120500';
    ctx.beginPath();
    ctx.arc(hx + 6, hy2 - 2, 4, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = '#b86020';
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    ctx.arc(hx + 6, hy2 - 2, 3, 0, Math.PI * 2);
    ctx.stroke();
    ctx.fillStyle = '#fff';
    ctx.beginPath();
    ctx.arc(hx + 7, hy2 - 3, 1.5, 0, Math.PI * 2);
    ctx.fill();
    ctx.fillStyle = '#6a2828';
    ctx.beginPath();
    ctx.ellipse(hx + 17, hy2 + 4, 2.5, 2, 0, 0, Math.PI * 2);
    ctx.fill();
    ctx.restore();
}
